<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6a1124a6d0c742ad13fae727a90601ae
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GO\\' => 3,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GO\\' => 
        array (
            0 => __DIR__ . '/..' . '/peppeocchi/php-cron-scheduler/src/GO',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/cron-expression/src/Cron',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6a1124a6d0c742ad13fae727a90601ae::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6a1124a6d0c742ad13fae727a90601ae::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
